function cite = MHS_cite(tPeriod,type)
% Copyright 2013, 2014 Thomas M. Mosier, Kendra V. Sharp, and David F. Hill
% This file is part of the GlobalClimateData Downscaling Package.
% 
% The GlobalClimateData Downscaling Package is free software: you can 
% redistribute it and/or modify it under the terms of the GNU General 
% Public License as published by the Free Software Foundation, either 
% version 3 of the License, or (at your option) any later version.
% 
% The Downscaling Package is distributed in the hope that it will be 
% useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with the Downscaling Package.  If not, see 
% <http://www.gnu.org/licenses/>.

if regexpbl(type,{'downscale','downscaling'})
    %Displays and outputs text directing users to paper citations and GNU GPL license.
    disp(['The GlobalClimateData.org Downscaling Package implements '...
        'methodologies and codes developed by Thomas M. Mosier, '...
        'David F. Hill, and Kendra V. Sharp.' char(10) ...
        'The scripts and functions associated with this work are ' ...
        'distributed under the GNU General Public License.' char(10) ...
        'When utilizing this work, please use the following citations for ' ...
        'the Downscaling Package and output data:' char(10)]);

    hisCite = ['Mosier, T. M., Hill, D. F., & Sharp, K. V. (2014). ' ...
            '30-Arcsecond monthly ' char(10) 'climate surfaces with ' ...
            'global land coverage. International Journal of Climatology,' ...
            char(10) ' 34(7), 2175-2188.'];
    futCite = ['Mosier, T. M. (2015, December). Characterizing Linkages '... 
        'between the Climate, ' char(10) 'Cryosphere, and Impacts on Run-of-River '...
        'Hydropower in Data-Sparse Mountain Environments' char(10)  ' (Dissertation).'...
        ' Oregon State University, Corvallis, OR, USA.'];


    if regexpbl(tPeriod, 'proj')
        cite = [hisCite char(10) futCite];
    elseif ~isempty(regexpi(tPeriod, 'his'))
        cite = hisCite;
    else
        error('MHS_cite:unknownTime', [char(39) tPeriod char(39) ...
            ' is an unkown time period.']);
    end
elseif regexpbl(type,{'CCHF','hydro'})
    %Displays and outputs text directing users to paper citations and GNU GPL license.
    disp(['The Conceptual Cryosphere Hydrology (CCHF) Package '...
        'implements methodologies and codes developed by Thomas M. Mosier, '...
        'David F. Hill, and Kendra V. Sharp.' char(10) ...
        'The scripts and functions associated with this work are ' ...
        'distributed under the GNU General Public License.' char(10) ...
        'When utilizing this work, please use the following citations for ' ...
        'the Downscaling Package and output data:' char(10)]);

    cite = ['Mosier, T. M., Hill, D. F., & Sharp, K. V. (in review; '...
            '2016). How Model Cryosphere Model Complexity is Just '...
            'Right? Exploration Using the Conceptual Cryosphere Hydrology Framework'];
end

disp(cite);

disp(['Please additionally cite all of the input data sources ' ...
    'utilized (e.g. from the Climate Research Unit, '...
    'Willmott & Matsuura, Global Precipitation Climatology Centre, '...
    'WorldClim, and/or the Global Historical Climatology Network).' char(10)]);